Remove unwrap in Rect::round_out
RazrFalcon/tiny-skia pull request #50
Opened 2022-06-21 21:13 UTC by Wardenfar

fix #49 

Removed unwrap and return an option.

2022-06-22 06:22 UTC, RazrFalcon commented
Thanks! 

Can you replace a rendering tests with just a simple test in `geom.rs`? Just for this function.

Also, `Rect::round` above `round_out` has the same issue, so you probably should update it too.

2022-06-23 15:52 UTC, Wardenfar commented
I have made the changes

2022-06-23 16:22 UTC, RazrFalcon requested changes

2022-06-23 16:22 UTC, RazrFalcon commented on src/geom.rs
> +    fn issue_49() {
Rename to `round_overflow`

2022-06-23 16:22 UTC, RazrFalcon commented on src/geom.rs
> +        let rect = Rect::from_xywh(300.0, -1.0, specific_value, 1.0).unwrap();
`let rect = Rect::from_xywh(1.0, 0.0, i32::MAX as f32, 1.0).unwrap();`

I think this would be more obvious. Or something along those lines

2022-06-23 16:56 UTC, RazrFalcon approved these changes

2022-06-23 17:00 UTC, merged

2022-06-23 17:00 UTC, RazrFalcon commented
Thanks!